[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dynamic_padding = true
padding.x = 2
padding.y = 2
decorations = "None"
title = "Alacritty"
dynamic_title = false
opacity = 0.95

[font]
size = 10.50
builtin_box_drawing = true

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[cursor]
style.shape = "Block"
style.blinking = "Never"
unfocused_hollow = true
thickness = 0.2
